version: "3.5"

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/zihirri/data/wordpress
      o: bind


  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/zihirri/data/mariadb
      o: bind

services:
  nginx:
    image: nginx
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    
  adminer:
    image: adminer
    build: ./requirements/bonus/adminer/
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8090:8090"
    networks:
      - inception
    restart: always

  redis:
    image: redis
    build: ./requirements/bonus/redis/
    container_name: redis
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  cadvisor:
    image: cadvisor
    build: ./requirements/bonus/cadvisor/
    container_name: cadvisor
    networks:
      - inception
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"

  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/zihirri/ftp/fi
    networks:
      - inception
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    restart: always